# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
# This file uses placeholders that will be replaced by ai-gen during deployment

client_id = "eaf544c73ccfc7dda41fb1e770a0e25f"
application_url = "https://my-shopify-app.tangjing.workers.dev"
embedded = true
name = "my-cf-app"
handle = "my-cf-app-123"

#dev_store_url = "https://dev-storeui.myshopify.com"

[build]

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://my-shopify-app.tangjing.workers.dev/auth/callback",
  "https://my-shopify-app.tangjing.workers.dev/auth/shopify/callback",
  "https://my-shopify-app.tangjing.workers.dev/api/auth/callback"
]

[pos]
embedded = false
